### ISSUE TITLE
Is this project complete or are more snippets regularly added?

### ISSUE THREAD

**Issue by ArhumJain** [isaac098098/latex-luasnips#1]
This is an amazing project that I'm going to learn and use thoroughly... That being said, are more snippets yet to be added?

**Comment by isaac098098** [comment]
Hey, thank you so much, honestly I decided to document all of my snippets for myself only, I write a lot. But I'm glad it was useful to you anyway.

I was thinking of adding snippets from the TikZ package to make images and diagrams, also commands from the xcolor package, the forest package, etc. But the truth is that right now and for a few years I will be quite busy and I don't think I'll be adding more in the near future. Feel free to add whatever you want, I also left this project not so advanced so anyone can add whatever they want. It's all about adding snippets that fit your needs, and there's little point in adding some you'll never use. That being said I thank you again for your words, I hope you learn to write quickly and get the most out of it.

I also strongly recommend reading the blogs by Gilles Castel and Ejmastnak that I mentioned at the beginning of the readme file, especially the latter, he explains all the technical details you'll ever need.


Obtener Outlook para Android<https://aka.ms/AAb9ysg>
________________________________
From: Arhum Jain ***@***.***>
Sent: Tuesday, October 22, 2024 8:55:58 PM
To: isaac098098/latex-luasnips ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [isaac098098/latex-luasnips] Is this project complete or are more snippets regularly added? (Issue #1)


This is an amazing project that I'm going to learn and use thoroughly... That being said, are more snippets yet to be added?
